# Generated by Django 5.2.6 on 2025-09-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
